### PR TITLE
Delimiters and eol settings via Coma::__construct()

### PR DESCRIPTION
**Pull request by rogeriopradoj**

### CODE REVIEW

**Comment by rogeriopradoj** [comment]
Ping @neko !

**Comment by clickbait** [comment]
sorry, was sleeping. looks good to me! thanks.

**Comment by rogeriopradoj** [comment]
Alright, thanks for accepting the suggestion.

I've seen https://github.com/ziadoz/awesome-php/pull/468, I think two great additions to this project would be:
- include tests
- create composer.json

Do you mind if I work on these things?

Best,

Rogerio

**Comment by clickbait** [comment]
I don't mind at all, that would be great. :)

**Pull request merged**
